"""add_psych_fields_safe

Revision ID: ec11a0100489
Revises: db7d812f5ddb
Create Date: 2025-12-25 18:45:38.141838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec11a0100489'
down_revision: Union[str, Sequence[str], None] = 'db7d812f5ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('motivation', sa.String(), nullable=True))
    op.add_column('habit', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('habit_log', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('habit_log', sa.Column('mood', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit_log', 'mood')
    op.drop_column('habit_log', 'note')
    op.drop_column('habit', 'duration_minutes')
    op.drop_column('habit', 'motivation')
    # ### end Alembic commands ###
